### ISSUE TITLE
This extension drops empty tags

### ISSUE THREAD

**Issue by alex-shamshurin** [Stolz/laravel-html-tidy#3]
Drops empty tags and no options provided to fix it. For example font awesome use <i class="fa fa..."></i>
but this extension cut it off

**Comment by Stolz** [comment]
The problem is the PHP Tidy extension uses the [original](http://tidy.sourceforge.net/) tidy implementation, which is designed for HTML4. In HTML4, only [a few](https://www.w3.org/TR/html4/index/elements.html) tags are allowed to be empty. Any tag that is empty and is not in that list will be removed.

[Newer](http://www.html-tidy.org/) version of Tidy has added the option [drop-empty-elements](http://api.html-tidy.org/tidy/quickref_5.1.25.html#drop-empty-elements) but until PHP does not use the new version there is nothing I can do about it since I'm not the author of the library, I just created a package that uses it.

You can try to declare new empty tags using the [new-empty-tags](http://tidy.sourceforge.net/docs/quickref.html) option (remember to also declare empty tags as either inline or blocklevel) but I didn't try this option myself.

**Comment by alex-shamshurin** [comment]
my solution was 

```
<i>&nbsp;</i>
```
